### ISSUE TITLE
Some Integrated Terminal Colours Barely Readable

### ISSUE THREAD

**Issue by chrislewisdev** [wyze/vscode-hybrid-next#4]
Although the new terminal colour scheme (#2) is great, unfortunately it looks like it has rendered some font colours practically unreadable.

Here's an example when specifying a command-line option e.g. `terraform init -no-color`:
![image](https://user-images.githubusercontent.com/395415/47191524-b24f6100-d393-11e8-8e42-89e1cf4ec394.png)

And here's the exact same command which is totally invisible with the grey background:
![image](https://user-images.githubusercontent.com/395415/47191545-dca11e80-d393-11e8-9edc-8bcbdec9a5bb.png)

This is especially troublesome with some error output, e.g.:
![image](https://user-images.githubusercontent.com/395415/47191573-08240900-d394-11e8-88de-6238cd5bd1ce.png)

I think that specific ANSI colour just needs to be changed to something which suits the background more. I'd make the update myself but I'm not too sure how to tell which colour needs changing.

**Comment by wyze** [comment]
For me, it looks like it is `ansiBlack` that is an offender. Or probably the `ansiBrightBlack`.

**Comment by chrislewisdev** [comment]
Thanks for the tip @wyze, I've opened #5 to address this now!

**Comment by wyze** [comment]
This has been released in [v2.3.1](https://github.com/wyze/vscode-hybrid-next/releases/tag/v2.3.1). Thanks again!
